global using Infrastructure.Services.Abstractions;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Microsoft.Extensions.Options;
global using AutoMapper;
global using Order.Host.Data;
global using Order.Host.Repositories.Abstractions;
global using Order.Host.Services;
global using Order.Host.Services.Abstractions;
